spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:/db/demo
    username: username
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    user: username
    password: password
    url: jdbc:h2:file:/db/demo
